name: spanish_words
description: >
  Utilities for working with Spanish words. Counts syllables, generates
  well-sounding word combinations, and provides access to the top 5000 Spanish
  words by usage.
version: 4.0.0
homepage: https://github.com/pcharleszemora/spanish_words

environment:
  sdk: '>=2.14.0 <3.3.1'

dependencies:
  string_scanner: ^1.1.0

dev_dependencies:
  # benchmark_harness: ^1.0.4
  test: ^1.16.8
